In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

In [2]:
import pandas as pd

file_path = r"C:\Users\sally\OneDrive\바탕 화면\25_1\guangginGu_project\소상공인시장진흥공단_상가(상권)정보_서울_202409.csv"

df = pd.read_csv(file_path, encoding="utf-8")  # 'utf-8' 인코딩 사용

print(df.head())  # 첫 5행 출력

C:\Users\sally\AppData\Local\Temp\ipykernel_17312\3756959305.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, encoding="utf-8")  # 'utf-8' 인코딩 사용

                 상가업소번호       상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드  \
0  MA0101202210A0093845     이상한스냅  NaN        M1    과학·기술      M113
1  MA010120220805430767       토끼정  NaN        I2       음식      I201
2  MA010120220805430797       가배차  NaN        I2       음식      I201
3  MA010120220805430812  비에이치씨항동점  NaN        I2       음식      I210
4  MA010120220805430834   무지개삼성약국  NaN        G2       소매      G215

    상권업종중분류명 상권업종소분류코드 상권업종소분류명 표준산업분류코드  ...                     건물관리번호  \
0      사진 촬영    M11301    사진촬영업   M73303  ...  1147010300100090004000001
1         한식    I20101   백반/한정식   I56111  ...  1150010500107740012000001
2         한식    I20101   백반/한정식   I56111  ...  1171010400101430002012823
3      기타 간이    I21006       치킨   I56193  ...  1153011200101000005000001
4  의약·화장품 소매    G21501       약국   G47811  ...  1168011400106840005002734

               건물명              도로명주소   구우편번호 신우편번호  동정보  층정보  호정보  \
0             백송주택  서울특별시 양천구 월정로 283  158822  7902  NaN  NaN  NaN
1            마커스빌딩  서울특별시 강서구 마곡동로 55  157805  7802  NaN    2  NaN
2           사이언스빌딩  서울특별시 송파구 가락로 209  138852  5663  NaN    1  NaN
3  항동중흥에스클래스베르데카운티  서울특별시 구로구 연동로 233  152140  8362  NaN    1  NaN
4             대훈빌딩   서울특별시 강남구 일원로 45  135516  6343  NaN  NaN  NaN

           경도         위도
0  126.828832  37.542117
1  126.833022  37.560053
2  127.116136  37.507170
3  126.820686  37.481640
4  127.081499  37.489893

[5 rows x 39 columns]

In [3]:
# 열 이름 알기
print(df.columns)

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [4]:
# 광진구만 뽑아내기
df_g = df[df['도로명주소'].str.contains("광진구", na=False)]
df_g

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
9,MA0101202210A0037544,영자's곱창,NaN,I2,음식,I201,한식,I20109,곱창 전골/구이,I56111,...,1121510100101690021003140,NaN,서울특별시 광진구 면목로 172,143900,4904,NaN,1,NaN,127.082832,37.568503
21,MA010120220805431191,맑은에스테틱,NaN,S2,수리·개인,S208,욕탕·신체관리,S20802,마사지/안마,S96122,...,1121510500100480053015378,NaN,서울특별시 광진구 뚝섬로32길 33,143843,5085,NaN,1,NaN,127.066814,37.534047
66,MA010120220805433802,썬더치킨,NaN,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1121510900101490006018973,NaN,서울특별시 광진구 군자로 127,143839,4999,NaN,1,NaN,127.073598,37.553662
81,MA010120220805433097,더봄,NaN,S2,수리·개인,S207,이용·미용,S20703,네일숍,S96119,...,1121510900100480036000001,NaN,서울특별시 광진구 면목로 7,143837,4999,NaN,1,NaN,127.075155,37.554936
186,MA010120220805437728,딘두오,NaN,G2,소매,G209,섬유·의복·신발 소매,G20908,가발 소매업,G47422,...,1121510100106360013000002,NaN,서울특별시 광진구 천호대로103길 8,143912,4920,NaN,NaN,NaN,127.075429,37.559362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465957,MA0101202406A0508197,광진출장홈케어,NaN,S2,수리·개인,S208,욕탕·신체관리,S20803,체형/비만 관리,S96129,...,1121510100106450007026314,NaN,서울특별시 광진구 긴고랑로14길 64,143912,4918,NaN,NaN,NaN,127.080041,37.559858
465980,MA0101202406A0439628,뚝섬로뚝섬유원지점,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,1121510500105530531012147,이주빌딩,서울특별시 광진구 뚝섬로 548,143193,5090,NaN,1,NaN,127.070837,37.534457
465989,MA0101202406A0500326,신전떡볶이,중곡점,I2,음식,I210,기타 간이,I21007,김밥/만두/분식,I56194,...,1121510100100300080000001,보건복지행정타운,서울특별시 광진구 능동로 400,143884,4933,NaN,NaN,NaN,127.084437,37.565046
466002,MA0101202406A0503441,부동산프라임공인중개사사무소,NaN,L1,부동산,L102,부동산 서비스,L10203,부동산 중개/대리업,L68221,...,1121510700100470022026147,NaN,서울특별시 광진구 아차산로27길 14,143917,5018,NaN,NaN,NaN,127.067867,37.542210
466018,MA0101202406A0466458,농가통닭,NaN,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1121510100100780011001161,NaN,서울특별시 광진구 영화사로 5,143887,4945,NaN,1,NaN,127.088365,37.558526

In [5]:
# 가장 중요한 상호명, 위도경도 null 있는지 확인
print(sum(df_g['상호명'].isnull()))

0

In [6]:
print(sum(df_g['경도'].isnull()))

0

In [7]:
print(sum(df_g['위도'].isnull()))

0

In [8]:
# 대분류명 종류 확인
df_g['상권업종대분류명'].value_counts()

상권업종대분류명
음식         4639
소매         3653
과학·기술      1952
수리·개인      1898
예술·스포츠      844
부동산         839
교육          823
시설관리·임대     703
보건의료        204
숙박          201
Name: count, dtype: int64

In [9]:
# 중분류명 종류 확인
df_g['상권업종중분류명'].value_counts()

상권업종중분류명
한식             1625
이용·미용          1161
기타 간이           981
부동산 서비스         839
섬유·의복·신발 소매     741
               ...
기타 보건            13
병원               11
시장 조사            11
장례식장              8
조경·유지             5
Name: count, Length: 74, dtype: int64

### 분석 위해 필요한 열만 생각해보기
- 상호명, 지점명, 상권업종대분류명, 상권업종중분류명, 상권업종소분류명, 도로명주소, 층정보, 법정동명, 경도, 위도


### 열 사용 방안
- 중분류로 업종 나누기
- 주소 간단히 합치기
- 가게 대표 서비스는 소분류명으로 생각
- 상호명, 지점명 합치기

In [11]:
df_gwangjin  = df_g[['상호명', '지점명', '상권업종대분류명', '상권업종중분류명', '상권업종소분류명', '도로명주소','법정동명', '층정보', '경도', '위도']]
df_gwangjin

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,도로명주소,법정동명,층정보,경도,위도
9,영자's곱창,NaN,음식,한식,곱창 전골/구이,서울특별시 광진구 면목로 172,중곡동,1,127.082832,37.568503
21,맑은에스테틱,NaN,수리·개인,욕탕·신체관리,마사지/안마,서울특별시 광진구 뚝섬로32길 33,자양동,1,127.066814,37.534047
66,썬더치킨,NaN,음식,기타 간이,치킨,서울특별시 광진구 군자로 127,군자동,1,127.073598,37.553662
81,더봄,NaN,수리·개인,이용·미용,네일숍,서울특별시 광진구 면목로 7,군자동,1,127.075155,37.554936
186,딘두오,NaN,소매,섬유·의복·신발 소매,가발 소매업,서울특별시 광진구 천호대로103길 8,중곡동,NaN,127.075429,37.559362
...,...,...,...,...,...,...,...,...,...,...
465957,광진출장홈케어,NaN,수리·개인,욕탕·신체관리,체형/비만 관리,서울특별시 광진구 긴고랑로14길 64,중곡동,NaN,127.080041,37.559858
465980,뚝섬로뚝섬유원지점,NaN,음식,한식,백반/한정식,서울특별시 광진구 뚝섬로 548,자양동,1,127.070837,37.534457
465989,신전떡볶이,중곡점,음식,기타 간이,김밥/만두/분식,서울특별시 광진구 능동로 400,중곡동,NaN,127.084437,37.565046
466002,부동산프라임공인중개사사무소,NaN,부동산,부동산 서비스,부동산 중개/대리업,서울특별시 광진구 아차산로27길 14,화양동,NaN,127.067867,37.542210
466018,농가통닭,NaN,음식,기타 간이,치킨,서울특별시 광진구 영화사로 5,중곡동,1,127.088365,37.558526

In [12]:
print(sum(df_gwangjin['층정보'].isnull()))

# 주소 간단히 합치기

df_gwangjin = pd.DataFrame(df_gwangjin)

def address(x):
    if pd.notnull(x['층정보']):  # '층정보' 열이 NaN이 아닐 경우
        return x['도로명주소'] + " (" + x['법정동명'] + ") " + str(x['층정보']) + "층"
    else:  # '층정보' 열이 NaN일 경우
        return x['도로명주소'] + " (" + x['법정동명'] + ")"


# '주소' 열 생성
df_gwangjin['주소'] = df_gwangjin.apply(address, axis=1)

# 결과 확인
print(df_gwangjin[['주소']])

4192
                                  주소
9         서울특별시 광진구 면목로 172 (중곡동) 1층
21      서울특별시 광진구 뚝섬로32길 33 (자양동) 1층
66        서울특별시 광진구 군자로 127 (군자동) 1층
81          서울특별시 광진구 면목로 7 (군자동) 1층
186       서울특별시 광진구 천호대로103길 8 (중곡동)
...                              ...
465957    서울특별시 광진구 긴고랑로14길 64 (중곡동)
465980    서울특별시 광진구 뚝섬로 548 (자양동) 1층
465989       서울특별시 광진구 능동로 400 (중곡동)
466002    서울특별시 광진구 아차산로27길 14 (화양동)
466018     서울특별시 광진구 영화사로 5 (중곡동) 1층

[15756 rows x 1 columns]

In [13]:
# 상호, 지점명 합치기
def name(x):
    if pd.notnull(x['지점명']):
        return x['상호명'] + " " + x['지점명']
    else:  # '층정보' 열이 NaN일 경우
        return x['상호명']

df_gwangjin['상호'] = df_gwangjin.apply(name, axis=1)

In [14]:
df_gwangjin

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,도로명주소,법정동명,층정보,경도,위도,주소,상호
9,영자's곱창,NaN,음식,한식,곱창 전골/구이,서울특별시 광진구 면목로 172,중곡동,1,127.082832,37.568503,서울특별시 광진구 면목로 172 (중곡동) 1층,영자's곱창
21,맑은에스테틱,NaN,수리·개인,욕탕·신체관리,마사지/안마,서울특별시 광진구 뚝섬로32길 33,자양동,1,127.066814,37.534047,서울특별시 광진구 뚝섬로32길 33 (자양동) 1층,맑은에스테틱
66,썬더치킨,NaN,음식,기타 간이,치킨,서울특별시 광진구 군자로 127,군자동,1,127.073598,37.553662,서울특별시 광진구 군자로 127 (군자동) 1층,썬더치킨
81,더봄,NaN,수리·개인,이용·미용,네일숍,서울특별시 광진구 면목로 7,군자동,1,127.075155,37.554936,서울특별시 광진구 면목로 7 (군자동) 1층,더봄
186,딘두오,NaN,소매,섬유·의복·신발 소매,가발 소매업,서울특별시 광진구 천호대로103길 8,중곡동,NaN,127.075429,37.559362,서울특별시 광진구 천호대로103길 8 (중곡동),딘두오
...,...,...,...,...,...,...,...,...,...,...,...,...
465957,광진출장홈케어,NaN,수리·개인,욕탕·신체관리,체형/비만 관리,서울특별시 광진구 긴고랑로14길 64,중곡동,NaN,127.080041,37.559858,서울특별시 광진구 긴고랑로14길 64 (중곡동),광진출장홈케어
465980,뚝섬로뚝섬유원지점,NaN,음식,한식,백반/한정식,서울특별시 광진구 뚝섬로 548,자양동,1,127.070837,37.534457,서울특별시 광진구 뚝섬로 548 (자양동) 1층,뚝섬로뚝섬유원지점
465989,신전떡볶이,중곡점,음식,기타 간이,김밥/만두/분식,서울특별시 광진구 능동로 400,중곡동,NaN,127.084437,37.565046,서울특별시 광진구 능동로 400 (중곡동),신전떡볶이 중곡점
466002,부동산프라임공인중개사사무소,NaN,부동산,부동산 서비스,부동산 중개/대리업,서울특별시 광진구 아차산로27길 14,화양동,NaN,127.067867,37.542210,서울특별시 광진구 아차산로27길 14 (화양동),부동산프라임공인중개사사무소
466018,농가통닭,NaN,음식,기타 간이,치킨,서울특별시 광진구 영화사로 5,중곡동,1,127.088365,37.558526,서울특별시 광진구 영화사로 5 (중곡동) 1층,농가통닭

In [15]:
# '상호명'에 '점'이 포함된 행만 필터링하여 보기
df_gwangjin_with_점 = df_gwangjin[df_gwangjin['상호명'].str.contains('점', na=False)]

# 결과 확인
print(df_gwangjin_with_점[['상호명']])

                     상호명
1086    크레버스영재교육센터광진제1지점
1227            크린업24화양점
1321            레스티오도서관점
1340         룩앤룩안경원스타시티점
1873            맘스터치군자역점
...                  ...
464633            단토리화양점
464637        빽다방광진이튼1차점
465471            한식주점낭만
465844       샹츠마라어린이대공원점
465980         뚝섬로뚝섬유원지점

[864 rows x 1 columns]

In [16]:
# 다 쓴 도로명주소, 법정동명, 층정보 삭제
df_gwangjin = df_gwangjin.drop(['법정동명', '층정보', '상호명', '지점명'], axis=1)
df_gwangjin

,상권업종대분류명,상권업종중분류명,상권업종소분류명,도로명주소,경도,위도,주소,상호
9,음식,한식,곱창 전골/구이,서울특별시 광진구 면목로 172,127.082832,37.568503,서울특별시 광진구 면목로 172 (중곡동) 1층,영자's곱창
21,수리·개인,욕탕·신체관리,마사지/안마,서울특별시 광진구 뚝섬로32길 33,127.066814,37.534047,서울특별시 광진구 뚝섬로32길 33 (자양동) 1층,맑은에스테틱
66,음식,기타 간이,치킨,서울특별시 광진구 군자로 127,127.073598,37.553662,서울특별시 광진구 군자로 127 (군자동) 1층,썬더치킨
81,수리·개인,이용·미용,네일숍,서울특별시 광진구 면목로 7,127.075155,37.554936,서울특별시 광진구 면목로 7 (군자동) 1층,더봄
186,소매,섬유·의복·신발 소매,가발 소매업,서울특별시 광진구 천호대로103길 8,127.075429,37.559362,서울특별시 광진구 천호대로103길 8 (중곡동),딘두오
...,...,...,...,...,...,...,...,...
465957,수리·개인,욕탕·신체관리,체형/비만 관리,서울특별시 광진구 긴고랑로14길 64,127.080041,37.559858,서울특별시 광진구 긴고랑로14길 64 (중곡동),광진출장홈케어
465980,음식,한식,백반/한정식,서울특별시 광진구 뚝섬로 548,127.070837,37.534457,서울특별시 광진구 뚝섬로 548 (자양동) 1층,뚝섬로뚝섬유원지점
465989,음식,기타 간이,김밥/만두/분식,서울특별시 광진구 능동로 400,127.084437,37.565046,서울특별시 광진구 능동로 400 (중곡동),신전떡볶이 중곡점
466002,부동산,부동산 서비스,부동산 중개/대리업,서울특별시 광진구 아차산로27길 14,127.067867,37.542210,서울특별시 광진구 아차산로27길 14 (화양동),부동산프라임공인중개사사무소
466018,음식,기타 간이,치킨,서울특별시 광진구 영화사로 5,127.088365,37.558526,서울특별시 광진구 영화사로 5 (중곡동) 1층,농가통닭

In [17]:
# 열 순서 변경
new_order = ['상호', '주소', '상권업종대분류명', '상권업종중분류명', '상권업종소분류명', '경도', '위도', '도로명주소']

df_gwangjin = df_gwangjin[new_order]

In [18]:
df_gwangjin.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15756 entries, 9 to 466018
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   상호        15756 non-null  object
 1   주소        15756 non-null  object
 2   상권업종대분류명  15756 non-null  object
 3   상권업종중분류명  15756 non-null  object
 4   상권업종소분류명  15756 non-null  object
 5   경도        15756 non-null  float64
 6   위도        15756 non-null  float64
 7   도로명주소     15756 non-null  object
dtypes: float64(2), object(6)
memory usage: 1.1+ MB

In [19]:
df_good = pd.read_excel(r"C:\Users\sally\OneDrive\바탕 화면\25_1\guangginGu_project\착한가격업소_광진구.xls", header=2)
df_good.head()

,번호,업종명,업소명,주요품목,가격,업소 전화번호,주소,주차여부,포장여부,배달여부,예약여부,남여화장실 구분여부,단체이용 가능여부,무선인터넷 제공여부,반려동물 동반여부,유아시설여부
0,1,한식,59년왕십리성수점,인삼왕갈비(300g),15000,02-462-6775,서울특별시 광진구 동일로4길 15 (자양동) 1층,NaN,NaN,NaN,O,NaN,O,NaN,NaN,NaN
1,2,미용업,가연미용실,커트,12000,NaN,서울특별시 광진구 아차산로30길 39 (자양동) 1층,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,미용업,갤러리헤어,미용료\n(파마),30000,02-465-3861,서울특별시 광진구 동일로72길 46 (중곡동),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,양식,겨울나그네,돈까스,5500,02-498-3650,서울특별시 광진구 능동로 147-1 (화양동),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,기타요식업,고은별,커피,3000,02-453-4933,서울특별시 광진구 자양로 177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_good.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   번호          72 non-null     int64
 1   업종명         72 non-null     object
 2   업소명         72 non-null     object
 3   주요품목        72 non-null     object
 4   가격          72 non-null     int64
 5   업소 전화번호     59 non-null     object
 6   주소          72 non-null     object
 7   주차여부        2 non-null      object
 8   포장여부        8 non-null      object
 9   배달여부        4 non-null      object
 10  예약여부        8 non-null      object
 11  남여화장실 구분여부  1 non-null      object
 12  단체이용 가능여부   3 non-null      object
 13  무선인터넷 제공여부  7 non-null      object
 14  반려동물 동반여부   2 non-null      object
 15  유아시설여부      0 non-null      float64
dtypes: float64(1), int64(2), object(13)
memory usage: 9.1+ KB

In [29]:
df_good['주소_추출'] = df_good['주소'].str.extract(r'^(.*? \d+)')

In [22]:
df_good.head()

,번호,업종명,업소명,주요품목,가격,업소 전화번호,주소,주차여부,포장여부,배달여부,예약여부,남여화장실 구분여부,단체이용 가능여부,무선인터넷 제공여부,반려동물 동반여부,유아시설여부,주소_추출
0,1,한식,59년왕십리성수점,인삼왕갈비(300g),15000,02-462-6775,서울특별시 광진구 동일로4길 15 (자양동) 1층,NaN,NaN,NaN,O,NaN,O,NaN,NaN,NaN,서울특별시 광진구 동일로4길 15
1,2,미용업,가연미용실,커트,12000,NaN,서울특별시 광진구 아차산로30길 39 (자양동) 1층,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서울특별시 광진구 아차산로30길 39
2,3,미용업,갤러리헤어,미용료\n(파마),30000,02-465-3861,서울특별시 광진구 동일로72길 46 (중곡동),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서울특별시 광진구 동일로72길 46
3,4,양식,겨울나그네,돈까스,5500,02-498-3650,서울특별시 광진구 능동로 147-1 (화양동),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서울특별시 광진구 능동로 147
4,5,기타요식업,고은별,커피,3000,02-453-4933,서울특별시 광진구 자양로 177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,서울특별시 광진구 자양로 177

In [33]:
matched_data = df_gwangjin[df_gwangjin['도로명주소'].isin(df_good['주소_추출'])]

matched_data

,상호,주소,상권업종대분류명,상권업종중분류명,상권업종소분류명,경도,위도,도로명주소
4712,성심공인중개사사무소,서울특별시 광진구 자양로18길 12 (구의동) 1층,부동산,부동산 서비스,부동산 중개/대리업,127.084096,37.537426,서울특별시 광진구 자양로18길 12
10009,업,서울특별시 광진구 아차산로 324 (자양동) 1층,과학·기술,광고,광고 대행업,127.078755,37.537448,서울특별시 광진구 아차산로 324
12237,동경에서먹었던규동,서울특별시 광진구 광나루로 373 (군자동) 1층,음식,일식,일식 카레/돈가스/덮밥,127.071560,37.548231,서울특별시 광진구 광나루로 373
16274,더수,서울특별시 광진구 자양로13길 79 (자양동) 1층,수리·개인,이용·미용,네일숍,127.080719,37.533174,서울특별시 광진구 자양로13길 79
17674,뚱배,서울특별시 광진구 긴고랑로 25 (중곡동),음식,주점,요리 주점,127.079283,37.563528,서울특별시 광진구 긴고랑로 25
...,...,...,...,...,...,...,...,...
452260,제노PCZONE,서울특별시 광진구 능동로16길 60 (화양동) 3층,예술·스포츠,유원지·오락,PC방,127.076283,37.545223,서울특별시 광진구 능동로16길 60
452655,곤지네일,서울특별시 광진구 광나루로17길 14 (군자동) 1층,수리·개인,이용·미용,네일숍,127.072771,37.548223,서울특별시 광진구 광나루로17길 14
454504,세미,서울특별시 광진구 아차산로51길 101 (구의동) 1층,음식,비알코올,카페,127.085279,37.541526,서울특별시 광진구 아차산로51길 101
457312,더벨르뷰티&왁싱,서울특별시 광진구 아차산로30길 39 (자양동) 2층,수리·개인,이용·미용,피부 관리실,127.067477,37.538990,서울특별시 광진구 아차산로30길 39
459308,부대사랑,서울특별시 광진구 능동로16길 57 (화양동) 2층,음식,한식,백반/한정식,127.076122,37.545374,서울특별시 광진구 능동로16길 57

In [24]:
matched_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 143 entries, 4712 to 459308
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   상호        143 non-null    object
 1   주소        143 non-null    object
 2   상권업종대분류명  143 non-null    object
 3   상권업종중분류명  143 non-null    object
 4   상권업종소분류명  143 non-null    object
 5   경도        143 non-null    float64
 6   위도        143 non-null    float64
 7   도로명주소     143 non-null    object
dtypes: float64(2), object(6)
memory usage: 10.1+ KB

In [25]:
from tabulate import tabulate

df_merged = df_gwangjin.merge(df_good, left_on='도로명주소', right_on='주소_추출', how='inner')

df_result = df_merged[['도로명주소', '상호']].rename(columns={'도로명주소': '도로명 주소', '상호': '상호명'}).sort_values(by='도로명 주소').reset_index(drop=True)

print(tabulate(df_result, headers='keys', tablefmt='pretty'))

+-----+------------------------------------+-------------------------------------------+
|     |            도로명 주소             |                  상호명                   |
+-----+------------------------------------+-------------------------------------------+
|  0  |   서울특별시 광진구 광나루로 373   |        삼성부동산공인중개사사무소         |
|  1  |   서울특별시 광진구 광나루로 373   |               아룸헤어살롱                |
|  2  |   서울특별시 광진구 광나루로 373   |                 빠오즈푸                  |
|  3  |   서울특별시 광진구 광나루로 373   |                  세종원                   |
|  4  |   서울특별시 광진구 광나루로 373   |            동경에서먹었던규동             |
|  5  | 서울특별시 광진구 광나루로17길 14  |                 네일드비                  |
|  6  | 서울특별시 광진구 광나루로17길 14  |                 곤지네일                  |
|  7  | 서울특별시 광진구 광나루로17길 14  |               스위트앤카츠                |
|  8  | 서울특별시 광진구 광나루로24길 20  |            타스더안주셀렉트샵             |
|  9  | 서울특별시 광진구 광나루로24길 20  |               세븐건국대점                |
| 10  | 서울특별시 광진구 광나루로24길 20  |             리플커피건국대점              |
| 11  |    서울특별시 광진구 군자로 102    |               베트남쌀국수                |
| 12  |    서울특별시 광진구 군자로 102    |             무한정수제돈까스              |
| 13  |    서울특별시 광진구 군자로 104    |          컴포즈커피광진능동로점           |
| 14  |    서울특별시 광진구 군자로 111    |           한일공인중개사사무소            |
| 15  |    서울특별시 광진구 군자로 111    |             석기시대짜장마을              |
| 16  |    서울특별시 광진구 군자로 111    |                  태양사                   |
| 17  |    서울특별시 광진구 군자로 111    |                와플그란데                 |
| 18  |    서울특별시 광진구 군자로 129    |                손수제치킨                 |
| 19  |    서울특별시 광진구 군자로 138    |           케이프로사진협동조합            |
| 20  |    서울특별시 광진구 군자로 138    |              새이화음악학원               |
| 21  |    서울특별시 광진구 군자로 138    |              새이화음악학원               |
| 22  |    서울특별시 광진구 군자로 138    |                예원사진관                 |
| 23  |    서울특별시 광진구 군자로 138    |           케이프로사진협동조합            |
| 24  |    서울특별시 광진구 군자로 138    |               방미헤어컬쳐                |
| 25  |    서울특별시 광진구 군자로 138    |                국수사랑채                 |
| 26  |    서울특별시 광진구 군자로 138    |                예원사진관                 |
| 27  |    서울특별시 광진구 군자로 138    |                옥돌바베큐                 |
| 28  |    서울특별시 광진구 군자로 138    |                옥돌바베큐                 |
| 29  |    서울특별시 광진구 군자로 138    |                국수사랑채                 |
| 30  |    서울특별시 광진구 군자로 138    |               방미헤어컬쳐                |
| 31  |    서울특별시 광진구 군자로 175    |                 보리&치킨                 |
| 32  |    서울특별시 광진구 군자로 175    |              왕십리막내곱창               |
| 33  |   서울특별시 광진구 긴고랑로 149   |               충남지물장식                |
| 34  |   서울특별시 광진구 긴고랑로 149   |                미도미용실                 |
| 35  |   서울특별시 광진구 긴고랑로 25    |                 정당구장                  |
| 36  |   서울특별시 광진구 긴고랑로 25    |                마니아우동                 |
| 37  |   서울특별시 광진구 긴고랑로 25    |              씨유중곡일동점               |
| 38  |   서울특별시 광진구 긴고랑로 25    |              급속냉동삼겹살               |
| 39  |   서울특별시 광진구 긴고랑로 25    |              딸기노래연습장               |
| 40  |   서울특별시 광진구 긴고랑로 25    |                   뚱배                    |
| 41  |   서울특별시 광진구 긴고랑로 25    |             이유트래블서비스              |
| 42  |   서울특별시 광진구 긴고랑로 39    |                  중국관                   |
| 43  | 서울특별시 광진구 긴고랑로11길 26  |                소문난맛집                 |
| 44  | 서울특별시 광진구 긴고랑로11길 26  |                 세실리아                  |
| 45  | 서울특별시 광진구 긴고랑로36길 35  |                영주머리방                 |
| 46  | 서울특별시 광진구 긴고랑로36길 35  |                LG종합장식                 |
| 47  |    서울특별시 광진구 능동로 147    |                   저니                    |
| 48  |    서울특별시 광진구 능동로 147    |        퍼스트부동산공인중개사무소         |
| 49  |    서울특별시 광진구 능동로 147    |                라이크살롱                 |
| 50  |  서울특별시 광진구 능동로16길 50   |                   위락                    |
| 51  |  서울특별시 광진구 능동로16길 57   |                 부대사랑                  |
| 52  |  서울특별시 광진구 능동로16길 57   |                커피브라더                 |
| 53  |  서울특별시 광진구 능동로16길 60   |                 메이커스                  |
| 54  |  서울특별시 광진구 능동로16길 60   |                 콩닭콩닭                  |
| 55  |  서울특별시 광진구 능동로16길 60   |                   하루                    |
| 56  |  서울특별시 광진구 능동로16길 60   |                  더개미                   |
| 57  |  서울특별시 광진구 능동로16길 60   |                제노PCZONE                 |
| 58  |  서울특별시 광진구 능동로39길 11   |                  달디빈                   |
| 59  |   서울특별시 광진구 능동로40길 3   |            리오스포토스튜디오             |
| 60  |   서울특별시 광진구 능동로40길 3   |                피어나왁싱                 |
| 61  |   서울특별시 광진구 능동로47길 4   |             용가네양지해신탕              |
| 62  |   서울특별시 광진구 능동로47길 4   |           좋은공인중개사사무소            |
| 63  |  서울특별시 광진구 능동로48길 75   |                헤어아이디                 |
| 64  |    서울특별시 광진구 동일로 444    |                다비다식당                 |
| 65  |  서울특별시 광진구 동일로24길 18   |             김미라헤어콜렉션              |
| 66  |  서울특별시 광진구 동일로24길 18   |                경일식자재                 |
| 67  |   서울특별시 광진구 동일로4길 15   |                59년왕십리                 |
| 68  |  서울특별시 광진구 동일로72길 46   |          디딤돌공인중개사사무소           |
| 69  |  서울특별시 광진구 동일로72길 46   |              행복을마시는집               |
| 70  |  서울특별시 광진구 동일로72길 46   |                  갤러리                   |
| 71  |  서울특별시 광진구 동일로72길 51   |             이삭홍두께칼국수              |
| 72  |  서울특별시 광진구 동일로72길 51   |             이삭홍두깨칼국수              |
| 73  |  서울특별시 광진구 동일로80길 23   |                  오목대                   |
| 74  |    서울특별시 광진구 뚝섬로 472    |                 이선장회                  |
| 75  |    서울특별시 광진구 뚝섬로 472    |            와이더블유컴퍼니자             |
| 76  |    서울특별시 광진구 뚝섬로 472    |                차우동짜장                 |
| 77  |    서울특별시 광진구 뚝섬로 472    |              둥지노래연습장               |
| 78  |    서울특별시 광진구 뚝섬로 472    |           행운공인중개사사무소            |
| 79  |    서울특별시 광진구 뚝섬로 472    |               전주생막걸리                |
| 80  |    서울특별시 광진구 뚝섬로 622    |                파드마헤어                 |
| 81  |    서울특별시 광진구 뚝섬로 678    |                  김가네                   |
| 82  |    서울특별시 광진구 뚝섬로 678    |              싱글벙글노래방               |
| 83  |    서울특별시 광진구 뚝섬로 678    |                 구름초밥                  |
| 84  |  서울특별시 광진구 뚝섬로24길 21   |                 베이지크                  |
| 85  |  서울특별시 광진구 뚝섬로46길 34   |          에스원공인중개사사무소           |
| 86  |  서울특별시 광진구 뚝섬로46길 34   |                 한양세탁                  |
| 87  |  서울특별시 광진구 뚝섬로46길 34   |              마끼아쥬드초이               |
| 88  |  서울특별시 광진구 뚝섬로46길 34   |                 웰빙마트                  |
| 89  |  서울특별시 광진구 뚝섬로49길 31   |                 머리천국                  |
| 90  | 서울특별시 광진구 뚝섬로52라길 65  |                제이플래닝                 |
| 91  | 서울특별시 광진구 뚝섬로52라길 65  |                동현세탁소                 |
| 92  |    서울특별시 광진구 면목로 57     |                채현헤어샵                 |
| 93  |    서울특별시 광진구 면목로 57     |          더키즈프리미엄키즈카페           |
| 94  |    서울특별시 광진구 면목로 57     |       부동산일번지공인중개사사무소        |
| 95  |    서울특별시 광진구 면목로 57     |               에코비앤에스                |
| 96  |   서울특별시 광진구 아차산로 324   |                    업                     |
| 97  |   서울특별시 광진구 아차산로 324   |             삼원자동차공업사              |
| 98  |   서울특별시 광진구 아차산로 324   |               삼천리자전거                |
| 99  |   서울특별시 광진구 아차산로 324   |              성심골프A/S센타              |
| 100 |   서울특별시 광진구 아차산로 324   |           규성부동산중개사무소            |
| 101 |   서울특별시 광진구 아차산로 324   |                  톱뉴스                   |
| 102 |   서울특별시 광진구 아차산로 324   |                 종로식당                  |
| 103 |   서울특별시 광진구 아차산로 324   |                브러쉬헤어                 |
| 104 |   서울특별시 광진구 아차산로 341   |                  홍벨로                   |
| 105 | 서울특별시 광진구 아차산로30길 39  |                 조양마트                  |
| 106 | 서울특별시 광진구 아차산로30길 39  |             대흥양다리바베큐              |
| 107 | 서울특별시 광진구 아차산로30길 39  |        황금부동산공인중개사사무소         |
| 108 | 서울특별시 광진구 아차산로30길 39  |               마달요가스쿨                |
| 109 | 서울특별시 광진구 아차산로30길 39  |               나우설비기술                |
| 110 | 서울특별시 광진구 아차산로30길 39  |              더벨르뷰티&왁싱              |
| 111 | 서울특별시 광진구 아차산로30길 39  |                국교떡볶이                 |
| 112 | 서울특별시 광진구 아차산로30길 39  |               세무회계우리                |
| 113 | 서울특별시 광진구 아차산로30길 39  |                  조양D·C                  |
| 114 | 서울특별시 광진구 아차산로30길 39  |            수완카페앤베이커리             |
| 115 | 서울특별시 광진구 아차산로30길 39  |             황금행정사사무소              |
| 116 | 서울특별시 광진구 아차산로30길 39  |                가연미용실                 |
| 117 | 서울특별시 광진구 아차산로30길 39  |              정인인터내셔널               |
| 118 | 서울특별시 광진구 아차산로51길 101 |                   세미                    |
| 119 | 서울특별시 광진구 아차산로51길 101 |                  마미가                   |
| 120 | 서울특별시 광진구 아차산로51길 101 |               또바치킨&족발               |
| 121 |   서울특별시 광진구 용마산로 128   |              스마일카서비스               |
| 122 |   서울특별시 광진구 용마산로 128   |              피자마우스치킨               |
| 123 |   서울특별시 광진구 용마산로 128   |               명품카모터스                |
| 124 |   서울특별시 광진구 용마산로 128   |              등촌샤브칼국수               |
| 125 |  서울특별시 광진구 용마산로24길 6  |              꿈을꾸는사람들               |
| 126 |  서울특별시 광진구 용마산로24길 6  |               서승미헤어단                |
| 127 |    서울특별시 광진구 자양로 177    |                  고은별                   |
| 128 |    서울특별시 광진구 자양로 183    |                제이필헤어                 |
| 129 |    서울특별시 광진구 자양로 183    |                커피공급소                 |
| 130 |    서울특별시 광진구 자양로 183    | 오케이부동산(02-444-4985)공인중개사사무소 |
| 131 |  서울특별시 광진구 자양로13길 79   |                   더수                    |
| 132 |  서울특별시 광진구 자양로13길 79   |                초원미장원                 |
| 133 |  서울특별시 광진구 자양로15길 100  |                 자양다방                  |
| 134 |  서울특별시 광진구 자양로18길 12   |                 당산오돌                  |
| 135 |  서울특별시 광진구 자양로18길 12   |           성심공인중개사사무소            |
| 136 |  서울특별시 광진구 자양로26길 10   |                   옛골                    |
| 137 |  서울특별시 광진구 자양로28길 10   |               청년고기장수                |
| 138 |  서울특별시 광진구 자양로28길 10   |                  정은정                   |
| 139 |  서울특별시 광진구 자양로45길 18   |              파랑노랑미용실               |
| 140 |  서울특별시 광진구 자양번영로 65   |                 무병장수                  |
| 141 |  서울특별시 광진구 자양번영로 65   |               뮤지컬컴퍼니                |
| 142 | 서울특별시 광진구 천호대로110길 27 |             홍천화로숯불구이              |
| 143 | 서울특별시 광진구 천호대로110길 27 |              놀자노래연습장               |
| 144 | 서울특별시 광진구 천호대로110길 27 |               브이브이에스                |
| 145 | 서울특별시 광진구 천호대로110길 50 |                   다몽                    |
| 146 | 서울특별시 광진구 천호대로110길 50 |              댄디쿠스튜디오               |
| 147 | 서울특별시 광진구 천호대로110길 50 |                능라도분식                 |
| 148 | 서울특별시 광진구 천호대로135길 8  |                  중원사                   |
+-----+------------------------------------+-------------------------------------------+

In [45]:
df_result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   도로명 주소  149 non-null    object
 1   상호명     149 non-null    object
dtypes: object(2)
memory usage: 2.5+ KB

In [31]:
# 문자열 앞뒤 공백 제거
df_gwangjin['상호'] = df_gwangjin['상호'].str.strip()
df_good['업소명'] = df_good['업소명'].str.strip()

df_matched = df_gwangjin.merge(df_good, left_on=['도로명주소', '상호'], right_on=['주소_추출','업소명'],how='inner')

# 결과 출력
print(df_matched[['도로명주소', '상호']])

                    도로명주소         상호
0     서울특별시 광진구 능동로39길 11        달디빈
1       서울특별시 광진구 군자로 175      보리&치킨
2     서울특별시 광진구 자양로45길 18    파랑노랑미용실
3       서울특별시 광진구 군자로 129      손수제치킨
4   서울특별시 광진구 아차산로51길 101        마미가
5       서울특별시 광진구 자양로 177        고은별
6    서울특별시 광진구 자양로15길 100       자양다방
7       서울특별시 광진구 자양로 183      제이필헤어
8        서울특별시 광진구 면목로 57      채현헤어샵
9    서울특별시 광진구 천호대로135길 8        중원사
10    서울특별시 광진구 능동로16길 60         하루
11   서울특별시 광진구 아차산로30길 39      가연미용실
12     서울특별시 광진구 광나루로 373        세종원
13      서울특별시 광진구 뚝섬로 472      차우동짜장
14    서울특별시 광진구 능동로16길 50         위락
15      서울특별시 광진구 군자로 138      옥돌바베큐
16      서울특별시 광진구 긴고랑로 39        중국관
17    서울특별시 광진구 자양로26길 10         옛골
18      서울특별시 광진구 동일로 444      다비다식당
19  서울특별시 광진구 천호대로110길 50      능라도분식
20      서울특별시 광진구 군자로 138     방미헤어컬쳐
21    서울특별시 광진구 동일로80길 23        오목대
22    서울특별시 광진구 능동로48길 75      헤어아이디
23     서울특별시 광진구 능동로40길 3  리오스포토스튜디오
24      서울특별시 광진구 긴고랑로 25      마니아우동
25      서울특별시 광진구 군자로 111   석기시대짜장마을
26   서울특별시 광진구 긴고랑로36길 35      영주머리방
27     서울특별시 광진구 긴고랑로 149      미도미용실
28    서울특별시 광진구 동일로72길 51   이삭홍두깨칼국수
29    서울특별시 광진구 뚝섬로24길 21       베이지크
30      서울특별시 광진구 뚝섬로 678       구름초밥

In [ ]:
df_matched.info()